[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
solc_version = "0.8.20" # 指定 Solidity 版本
optimizer = true
optimizer_runs = 200
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read-write", path = "./" }]
gas_reports = ["*"]
via_ir = true
evm_version = "cancun"

[rpc_endpoints]
westend = "${ASSET_HUB_RPC_URL}"

[etherscan]
# westend = { key = "${WESTEND_API_KEY}", chain = "${CHAIN_ID}", url = "https://westend.api.subscan.io"}

[profile.ci.fuzz]
runs = 10_000
